DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    ID VARCHAR(100) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL
);

INSERT INTO MEMBER(ID,PASSWORD,NAME,ADDRESS) VALUES ('USER01','USER01','홍수민','구리시');

SELECT * FROM MEMBER;   

COMMIT;