CREATE TABLE MEMBER2(
    MEMBERID VARCHAR2(100)PRIMARY KEY,
    MEMBERPASS VARCHAR2(150) NOT NULL,
    MEMBERNAME VARCHAR2(150) NOT NULL,
    MEMBERADDR VARCHAR2(200) NOT NULL
      );
      INSERT INTO MEMBER2(MEMBERID, MEMBERPASS, MEMBERNAME, MEMBERADDR) SELECT ID, PASSWORD, NAME, ADDRESS FROM MEMBER;
      COMMIT;
      SELECT * FROM MEMBER2;